name: Deploy no AWS Elastic Beanstalk

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      OPENAI_API: ${{ secrets.OPENAI_API }}
      SONAR_TOKEN:    ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: https://sonarcloud.io

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Instalar dependências & coverage
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage pytest

      - name: Rodar testes e gerar relatório de coverage
        run: |
          coverage run -m pytest
          coverage xml -o coverage.xml

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Instalar SonarScanner CLI
        run: |
          SCANNER_VERSION=4.8.1.3023
          curl -sSLo sonar-scanner.zip \
            https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SCANNER_VERSION}-linux.zip
          unzip sonar-scanner.zip
          echo "${{ github.workspace }}/sonar-scanner-${SCANNER_VERSION}-linux/bin" >> $GITHUB_PATH

      - name: Executar análise SonarCloud
        env:
          SONAR_TOKEN:    ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
          JAVA_HOME:      ${{ env.JAVA_HOME_17_X64 }}
          PATH:           ${{ env.JAVA_HOME_17_X64 }}/bin:${{ env.PATH }}
        run: |
          # confirma que agora é Java 17
          java -version
          sonar-scanner \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.organization=marcos-gjr \
            -Dsonar.projectKey=Marcos-gjr_backend-level-1 \
            -Dsonar.sources=. \
            -Dsonar.tests=tests \
            -Dsonar.python.coverage.reportPaths=coverage.xml

      - name: Gerar arquivo .env
        run: |
          echo "OPENAI_API=${OPENAI_API}" > .env

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1

      - name: Empacotar código
        run: zip -r deploy.zip .

      - name: Enviar bundle para S3
        run: |
          aws s3 cp deploy.zip \
            s3://elasticbeanstalk-us-east-1-107193530096/deploy-${{ github.sha }}.zip

      - name: Criar nova versão do EB
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name backendapp \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket="elasticbeanstalk-us-east-1-107193530096",S3Key="deploy-${{ github.sha }}.zip"

      - name: Atualizar environment
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name Backend-deploy-env \
            --version-label ${{ github.sha }}