name: Deploy no AWS Elastic Beanstalk

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}



    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar arquivo .env
        run: |
          echo "OPENAI_API_KEY=${OPENAI_API_KEY}" > .env  

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1

      - name: Empacotar código
        run: zip -r deploy.zip .

      - name: Enviar bundle para S3
        run: |
          aws s3 cp deploy.zip \
            s3://elasticbeanstalk-us-east-1-107193530096/deploy-${{ github.sha }}.zip

      - name: Criar nova versão do EB
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name backendapp \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket="elasticbeanstalk-us-east-1-107193530096",S3Key="deploy-${{ github.sha }}.zip"

      - name: Atualizar environment
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name Backendapp-env \
            --version-label ${{ github.sha }}
